### PR TITLE
Release 1.0.4 to master

### PR DESCRIPTION
**Pull request by derpoliuk**

### CODE REVIEW

**Comment by derpoliuk** [comment]
Ready for review. CC @salutis @mikemee

**Review by rudolf-adamkovic — APPROVED** [review]

**Comment by derpoliuk** [comment]
@salutis thanks!

**Comment by derpoliuk** [comment]
Merged and tagged on `master`.

**Comment by rudolf-adamkovic** [comment]
@derpoliuk Great job, thanks!

**Pull request merged**
