### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by rudolf-adamkovic**

### CODE REVIEW

**Comment by rudolf-adamkovic** [comment]
@mikemee @andris-zalitis @derpoliuk Ready for review.

**Comment by derpoliuk** [comment]
@salutis FYI: there's conflict.

Does ReceiptKit work on OS X?

**Comment by rudolf-adamkovic** [comment]
@derpoliuk 

> FYI: there's conflict.

Thanks! Fixed.

> Does ReceiptKit work on OS X?

No idea.

**Comment by rudolf-adamkovic** [comment]
@mikemee @andris-zalitis @derpoliuk Ready for review again!

**Review by derpoliuk — APPROVED** [review]
LGTM.

**Comment by derpoliuk** [comment]
@salutis great job with updating. But Travis failed.

**Comment by rudolf-adamkovic** [comment]
@derpoliuk 

> But Travis failed.

😡 Restarted.

**Review by mikemee — CHANGES_REQUESTED** [review]
Likely due to a merge snafu, the info about CocoaPods is being restored. I removed this as part of the Swift3 build cleanup (see https://github.com/eggheadgames/apple-receipt/pull/24/commits/cdadc3c159c52e497470e33b92785972b911447a#diff-04c6e90faac2675aa89e2176d2eec7d8)

@salutis Please remove the `### CocoaPods` section, as it no longer applies. Thx!

**Comment by mikemee** [comment]
Other than CocoaPods reference, this looks great, thx!

**Comment by rudolf-adamkovic** [comment]
@mikemee 

> @salutis Please remove the ### CocoaPods section, as it no longer applies. Thx!

Done.

**Comment by rudolf-adamkovic** [comment]
@mikemee @andris-zalitis @derpoliuk Ready for review.

**Review by mikemee — APPROVED** [review]

**Pull request merged**
